spring:
  profiles: wnn001
server:
  port: 8761
eureka:
  instance:
    hostname: wnn001
  client:
    serviceUrl:
      defaultZone: http://wnn002/eureka/

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: wnn002
server:
  port: 8762
eureka:
  instance:
    hostname: wnn002
  client:
    serviceUrl:
      defaultZone: http://wnn001/eureka/
  
